### ISSUE TITLE
Peer To Peer Coding Review

### ISSUE THREAD

**Issue by ticoniq** [Fombi-Favour/Microverse-portfolio#9]
Your project is looking good you just need to make a few changes. ✔✔

- Please always try to add the alt element text in your <img>. You can imagine a scenario where a user's internet is very slow and not able to load the media of the website, in this kind of situation, 👍 🤗 👍 this alt element will help the user to understand what the media is all about. 👍 👍
- I think is best practice to have only one main tag on your code ✔✔

**Comment by marvin-nyalik** [comment]
Great job implementing the project as per the requirements✔✔. Kindly remember to include only one h1 tag in your project for the best SEO rankings. For more information about this check out [this article.](https://www.investisdigital.com/blog/seo/using-h1-tag-improves-search-engine-ranking#:~:text=Your%20website%20should%20have%20only,tags%20in%20the%20page%20code)

**Comment by hassanShakur** [comment]
Nice work on the project ✅. Just a minor improvement you might consider is using the `background` shorthand with a syntax that goes like this: `background: background-color background-image background-repeat background-attachment background-position`. This might not change the effect of the properties but is a nice little trick to reduce the amount of code 😄 .
